### ISSUE TITLE
Unable to turn off health checks

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#119]
## The problem

Removing the `healthCheck` block from the Backend Service configuration (in the origins file) does not disable the health checks. 

## Detailed description

To reproduce: 

1) Configure backend service as follows:
```
- id: "app"
  path: "/"
  connectionPool:
    maxConnectionsPerHost: 45
    maxPendingConnectionsPerHost: 15
    socketTimeoutMillis: 120000
    connectTimeoutMillis: 1000
    pendingConnectionTimeoutMillis: 8000
  responseTimeoutMillis: 60000
  origins:
  - { id: "app1", host: "localhost:9090" }
  - { id: "app2", host: "localhost:9091" }
```

2) Ensure nothing is listening on ports 9090 or 9091.

3) Start styx, and observe how health checker will mark the origins as inactive. But of course it shouldn't because health checking had been disabled.

## Acceptance criteria

1) This was a regression, suggesting we were missing an e2e test case for this. Ensure there is an e2e test for this.

2) When `healthCheck` block is absent, styx doesn't perform health checks, and unreachable origins will show up as active.
