### ISSUE TITLE
Sanitise HTTP message logs

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#454]
# Problem Statement

Styx logs HTTP messages for access logs, errors, warnings and so on. The messages are constructed by `toString` method, which includes all HTTP fields in verbatim, including sensitive information like security tokens.

Styx needs a configurable mechanism to sanitise the HTTP messages before logging them.

# Acceptance Criteria

- Remove `toString` method from `HttpRequest`, `HttpResponse`, `LiveHttpRequest`, `LiveHttpResponse`, and any possible base classes. This is to prevent developers from logging them accidentally.

- Add a "removeCookies" option, that is a list of cookie names, in styx server under `request-logging` section. Any cookie name in this list gets removed from the logged message output.
 
```
    request-logging:
      inbound:
          ...
      outbound:
          ...
      removeCookies:
         - sessionToken
         - anotherToken
```

- TODO: do we need `removeHeaders` option. Similar to `removeCookies` above.

- The new config is documented in styx end user manual.

- The new config option is added to styx config validator, so that it can pick up any invalid configuration.
