### ISSUE TITLE
Add plugins support for origins backwards compatibility mode

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#466]
## Description

Translate plugins configuration to routing objects, when the backwards compatibility mode (PR #458) is activated.

## Background

PR #458 added a "backwards compatibility mode" for origins-file based application routing. In the backwards compatibility mode Styx configures its forwarding path according to `origins.yaml` but at the moment it doesn't support external plugins.

To conclude the backwards compatibility mode work, Styx must apply the plugins configuration (in styx server configuration) to the forwarding path.

## Detailed Description

The plugins are loaded from the styx server configuration, and they will be available in `StyxServerComponents` class. But they are not automatically applied to the forwarding path when object based routing is used. Styx wouldn't know where to apply them. The plugins would have to be inserted at a desirable point in the forwarding path using the `InterceptorPipeline` object.

In the backwards compatibility mode the plugins should be applied at the beginning of the HTTP pipeline. We should create an `InterceptorPipeline` object, configure this with the plugins, and insert the object in HTTP pipeline root, just before the `PathPrefixRouter` object. The forwarding path will thus look like this:

```
routingObjects:
  root:
    type: HttpPipelineHandler
    config:
       plugins:
        - firstPlugin
        - secondPlugin
        - andSoOn
        - theLastPlugin
       handler: pathPrefixRouter

httpPipeline: root
```

## Acceptance Criteria

* A `HttpPipelineHandler` is created for the plugins, and inserted as `httpPipeline` root object.
* The `HttpPipelineHandler` pipeline contains the plugins in the order described by `plugins.all` attribute.
* The `HttpPipelineHandler` handler attribute points to the `PathPrefixRouter` object.
* The `HttpPipelineHandler` shall be called `pluginPipeline`. An end-user needs to use this name to route traffic to it. Like so:

``` httpPipeline: pluginPipeline```

* Plugins reload is not supported. A server restart is required to reload the plugins.

**Comment by mikkokar** [comment]
This doesn't necessarily need any code changes. The end-user can still configure its `httpPipelineRoot` with `HttpInterceptorPipeline`:

```
plugins:
  all:
    plugA: ...
    plugB: ... 
    plugC: ...

httpPipeline:
  type: HttpInterceptorPipeline:
  config:
    pipeline:
      - plugA
      - plugB
      - plugC
    handler: pathPrefixRouter
```

I recon this should work.
