### ISSUE TITLE
Provider object endpoints admin page

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#516]
## Description
Implement a *providers index* admin interface page that shows provider object endpoints. This is conceptually similar to `/admin/plugins`.

It should show:
- a header with service provider name, and the object type
- a list of admin endpoint links

## Acceptance Criteria

1. Shows a list of admin interface endpoints beside the provider name and type. For example, given the following provider:

```
providers:
  originsFileLoader:
    type: YamlFileConfigurationService
    config:
      originsFile: ${originsFile.absolutePath}
      monitor: True
      pollInterval: PT0.1S 
  abcHealthMonitor:
    type: HealthCheckMonitor
    config:
      object: abc

```

Should show:

---
### originsFileLoader (YamlFileConfigurationService)
- status
- origins
- etc

### abcHealthMonitor (HealthCheckMonitor)
- status
- someOtherEndpoint
---
2. This providers index page should be available via `/admin/providers` endpoint.

3. The main styx index page (`/admin`) has a visible link to the providers index page.
