### ISSUE TITLE
Resolve routing object name clashes

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#529]
We recently added support for multiple backend service providers for the routing object engine (https://github.com/HotelsDotCom/styx/issues/519).

However, the resulting routing objects should be prefixed with the provider name to avoid possible routing object name clashes. Consider the following two origin files:

origins.yml:
```
- id: "origin"
  path: "/"
  healthCheck:
    uri: /hello.txt
  origins:
    - { id: "origin-01", host: "origin:8080" }
```

origins-green.yml:
```
- id: "origin"
  path: "/"
  healthCheck:
    uri: /hello.txt
  origins:
    - { id: "origin-01", host: "otherhost:8080" }
```

They would be translated to `LoadBalancingGroup` and `HostProxy` objects with clashing names. To rectify this the object names shall be prefixed with the provider name.
